version: "3.6"

services:
  db:
    image: postgres:15.4-alpine3.18
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    depends_on:
      - db
    environment:
      - LOCAL=localhost
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

